// <auto-generated />
using System;
using AutomationManager.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutomationManager.Infrastructure.Migrations
{
    [DbContext(typeof(AutomationDbContext))]
    [Migration("20260213032848_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutomationManager.Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("AutomationManager.Domain.Entities.ExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("AutomationManager.Domain.Entities.ScriptCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("AutomationManager.Domain.Entities.ScriptCommandGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ScriptTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ScriptTemplateId");

                    b.ToTable("CommandGroups");
                });

            modelBuilder.Entity("AutomationManager.Domain.Entities.ScriptExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentCommand")
                        .HasColumnType("text");

                    b.Property<string>("NextCommands")
                        .HasColumnType("text");

                    b.Property<string>("PreviousCommands")
                        .HasColumnType("text");

                    b.Property<Guid>("ScriptTemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ScriptTemplateId");

                    b.ToTable("Executions");
                });

            modelBuilder.Entity("AutomationManager.Domain.Entities.ScriptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("LoopCount")
                        .HasColumnType("integer");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScriptText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ScriptTemplates");
                });

            modelBuilder.Entity("AutomationManager.Domain.Entities.ExecutionLog", b =>
                {
                    b.HasOne("AutomationManager.Domain.Entities.ScriptExecution", "Execution")
                        .WithMany("Logs")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Execution");
                });

            modelBuilder.Entity("AutomationManager.Domain.Entities.ScriptCommand", b =>
                {
                    b.HasOne("AutomationManager.Domain.Entities.ScriptCommandGroup", "Group")
                        .WithMany("Commands")
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("AutomationManager.Domain.Entities.ScriptCommandGroup", b =>
                {
                    b.HasOne("AutomationManager.Domain.Entities.ScriptTemplate", "ScriptTemplate")
                        .WithMany("Groups")
                        .HasForeignKey("ScriptTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScriptTemplate");
                });

            modelBuilder.Entity("AutomationManager.Domain.Entities.ScriptExecution", b =>
                {
                    b.HasOne("AutomationManager.Domain.Entities.Agent", "Agent")
                        .WithMany("Executions")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutomationManager.Domain.Entities.ScriptTemplate", "ScriptTemplate")
                        .WithMany("Executions")
                        .HasForeignKey("ScriptTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("ScriptTemplate");
                });

            modelBuilder.Entity("AutomationManager.Domain.Entities.Agent", b =>
                {
                    b.Navigation("Executions");
                });

            modelBuilder.Entity("AutomationManager.Domain.Entities.ScriptCommandGroup", b =>
                {
                    b.Navigation("Commands");
                });

            modelBuilder.Entity("AutomationManager.Domain.Entities.ScriptExecution", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("AutomationManager.Domain.Entities.ScriptTemplate", b =>
                {
                    b.Navigation("Executions");

                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
